[package]
name = "quint-connect"
version = "0.1.0"
edition = "2024"

[dependencies]
quint-connect-macros = { workspace = true }

anyhow = "1.0.100"
itf = "0.4.0"
serde = "1.0.228"
serde_json = "1.0.145"
tempdir = "0.3.7"

[dev-dependencies]
trybuild = { version = "1.0.114", features = ["diff"] }
